name: Test HydroSight on GitHub-Hosted Runner
on:
  push:
    branches:
    - master
    - release/*
jobs:
  my-job:
    name: Run MATLAB Commands
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run tests
        uses: matlab-actions/run-tests@v1.3.2
        with:    
          use-parallel: false # optional
          select-by-folder: # optional, default is 
          test-results-junit: testing/results.xml
          code-coverage-cobertura: testing/coverage.xml
